import { FormField } from "@/hooks/types";

export const LandType: FormField[] = [
  {
    type: "select",
    required: true,
    label: "User ID",
    name: "userId",
    placeholder: "Select user",
    options: [],
  },
  {
    name: "name",
    type: "text",
    required: true,
    label: "Land Name",
    placeholder: "Enter Name",
  },
  {
    name: "pinCode",
    maxLength: 6,
    required: true,
    label: "PinCode",
    type: "stringNumeric",
    placeholder: "Enter pincode",
  },
  {
    type: "text",
    required: true,
    name: "khasraNumber",
    label: "Khasra Number",
    placeholder: "Enter khasra Number",
  },
  {
    name: "area",
    maxLength: 10,
    required: true,
    label: "Area",
    type: "stringNumeric",
    placeholder: "Enter area",
  },
  {
    type: "select",
    required: true,
    name: "measuringUnit",
    label: "Measuring Unit",
    placeholder: "Select unit",
    options: [
      { label: "Bigha", value: "Bigha" },
      { label: "Biswa", value: "Biswa" },
      { label: "Kanal", value: "Kanal" },
      { label: "Marla", value: "Marla" },
      { label: "Acre", value: "Acre" },
      { label: "Hectare", value: "Hectare" },
      { label: "Square Feet", value: "Square Feet" },
      { label: "Square Meter", value: "Square Meter" },
      { label: "Square Yard", value: "Square Yard" },
      { label: "Guntha", value: "Guntha" },
      { label: "Ground", value: "Ground" },
      { label: "Cent", value: "Cent" },
      { label: "Katha", value: "Katha" },
      { label: "Decimal", value: "Decimal" },
      { label: "Ankanam", value: "Ankanam" },
    ],
  },
  {
    type: "br",
    name: "address",
    label: "Co-ordinates",
    widthFull: true,
  },
  {
    type: "text",
    required: true,
    name: "xLeftCoOrdinate",
    label: "X Left Coordinate",
    placeholder: "Enter X Left Coordinate",
  },
  {
    type: "text",
    required: true,
    name: "xRightCoOrdinate",
    label: "X Right Coordinate",
    placeholder: "Enter X Right Coordinate",
  },
  {
    type: "text",
    required: true,
    name: "yTopCoOrdinate",
    label: "Y Top Coordinate",
    placeholder: "Enter Y Top Coordinate",
  },
  {
    type: "text",
    required: true,
    name: "yBottomCoOrdinate",
    label: "Y Bottom Coordinate",
    placeholder: "Enter Y Bottom Coordinate",
  },
];
